<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dbradar</groupId>
    <artifactId>ddlcheck-pg</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>ddlcheck-pg</name>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
        <maven.dependency.plugin.version>3.8.1</maven.dependency.plugin.version>
        <maven.surefire.plugin.version>3.2.5</maven.surefire.plugin.version>
        <maven.shade.plugin.version>3.6.1</maven.shade.plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>apiguardian-api</artifactId>
            <version>1.1.2</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/apiguardian-api-1.1.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>asciitable</artifactId>
            <version>0.3.2</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/asciitable-0.3.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>auto-service</artifactId>
            <version>1.1.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/auto-service-1.1.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>auto-service-annotations</artifactId>
            <version>1.1.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/auto-service-annotations-1.1.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>collections-generic</artifactId>
            <version>4.01</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/collections-generic-4.01.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.5.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/commons-cli-1.5.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>grammar-core</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/grammar-core-1.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.annotation</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.annotation.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.ejb</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.ejb.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.jms</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.jms.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.persistence</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.persistence.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.resource</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.resource.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.servlet</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.servlet.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.servlet.jsp</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.servlet.jsp.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.servlet.jsp.jstl</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.servlet.jsp.jstl.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>javax.transaction</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/javax.transaction.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/jaxb-api-2.3.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>jcommander</artifactId>
            <version>1.82</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/jcommander-1.82.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.8.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/junit-jupiter-5.8.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.8.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/junit-jupiter-api-5.8.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/junit-jupiter-engine-5.8.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>5.8.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/junit-jupiter-params-5.8.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>junit-platform-commons</artifactId>
            <version>1.8.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/junit-platform-commons-1.8.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>1.8.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/junit-platform-engine-1.8.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>luaj-jse</artifactId>
            <version>3.0.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/luaj-jse-3.0.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.5.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/mockito-core-5.5.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>opentest4j</artifactId>
            <version>1.2.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/opentest4j-1.2.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.27</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/postgresql-42.2.27.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local.libs</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.9</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/slf4j-simple-2.0.9.jar</systemPath>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <compilerArgs>
                        <arg>-proc:none</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven.dependency.plugin.version}</version>
                <executions>
                    <execution>
                        <id>unpack-system-libs</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>system</includeScope>
                            <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                            <excludes>META-INF/*.SF,META-INF/*.DSA,META-INF/*.RSA,META-INF/MANIFEST.MF,module-info.class,META-INF/versions/**/module-info.class</excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <useModulePath>false</useModulePath>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven.shade.plugin.version}</version>
                <executions>
                    <execution>
                        <id>package-fat-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>all</shadedClassifierName>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>module-info.class</exclude>
                                        <exclude>META-INF/versions/**/module-info.class</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>dbradar.Main</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
