package dbradar.common.query.generator.data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import dbradar.GlobalState;
import dbradar.Randomly;
import dbradar.common.query.generator.config.DBConfig;
import dbradar.common.schema.AbstractTableColumn;

public class GeneratorRegister {

    private static GeneratorRegister register = null;

    private Map<String, Generator> basicGenerators = null;
    private Map<String, Generator> composeGenerators = null;

    private GeneratorRegister(GlobalState globalState) {
        initBasicGenerators();
        initComposeGenerators(globalState.getGeneratorConfigPath());
    }

    public static Generator getGenerator(AbstractTableColumn<?, ?> column, GlobalState globalState) {
        if (register == null) {
            register = new GeneratorRegister(globalState);
        }
        return register.getGeneratorInternal(column);
    }

    private Generator getGeneratorInternal(AbstractTableColumn<?, ?> column) {
        Generator generator;
        String type = column.getType().toString().toLowerCase();
        generator = composeGenerators.get(type);
        generator = (generator == null) ? basicGenerators.get(type) : generator;

        if (Objects.equals(type, "none")) {
            // According to the sqlancer code, the value type generated by the none type
            // data column is TEXT.
            generator = basicGenerators.get("text");
        }

        if (generator == null) {
            // TODO: the column type may be none(t1.c1:NONE), resulting in the error
            // Generator Register: cannot find the corresponding data generator for none
            throw new RuntimeException("Generator Register: cannot find the corresponding data generator for " + type);
        }

        return generator;
    }

    public static Map<String, Generator> getBasicGenerators(GlobalState globalState) {
        if (register == null) {
            register = new GeneratorRegister(globalState);
        }
        return register.basicGenerators;
    }

    private void initBasicGenerators() {

        // TODO refactor

        basicGenerators = new HashMap<>();

        basicGenerators.put("digit", new IntGenerator(0, 9, ""));
        basicGenerators.put("char", new CharGenerator());

        basicGenerators.put("date",
                new TemporalGenerator(TemporalGenerator.TemporalType.YEAR, TemporalGenerator.TemporalType.DAY));
        basicGenerators.put("year",
                new TemporalGenerator(TemporalGenerator.TemporalType.YEAR, TemporalGenerator.TemporalType.YEAR));
        basicGenerators.put("month",
                new TemporalGenerator(TemporalGenerator.TemporalType.MONTH, TemporalGenerator.TemporalType.MONTH));
        basicGenerators.put("day",
                new TemporalGenerator(TemporalGenerator.TemporalType.DAY, TemporalGenerator.TemporalType.DAY));
        basicGenerators.put("hour",
                new TemporalGenerator(TemporalGenerator.TemporalType.HOUR, TemporalGenerator.TemporalType.HOUR));
        basicGenerators.put("minute",
                new TemporalGenerator(TemporalGenerator.TemporalType.MINUTE, TemporalGenerator.TemporalType.MINUTE));
        basicGenerators.put("second",
                new TemporalGenerator(TemporalGenerator.TemporalType.SECOND, TemporalGenerator.TemporalType.SECOND));
        basicGenerators.put("microsecond", new TemporalGenerator(TemporalGenerator.TemporalType.MICROSECOND,
                TemporalGenerator.TemporalType.MICROSECOND));
        basicGenerators.put("time",
                new TemporalGenerator(TemporalGenerator.TemporalType.HOUR, TemporalGenerator.TemporalType.SECOND));
        basicGenerators.put("datetime",
                new TemporalGenerator(TemporalGenerator.TemporalType.YEAR, TemporalGenerator.TemporalType.SECOND));
        basicGenerators.put("second_microsecond", new TemporalGenerator(TemporalGenerator.TemporalType.SECOND,
                TemporalGenerator.TemporalType.MICROSECOND));
        basicGenerators.put("minute_microsecond", new TemporalGenerator(TemporalGenerator.TemporalType.MINUTE,
                TemporalGenerator.TemporalType.MICROSECOND));
        basicGenerators.put("minute_second",
                new TemporalGenerator(TemporalGenerator.TemporalType.MINUTE, TemporalGenerator.TemporalType.SECOND));
        basicGenerators.put("hour_microsecond",
                new TemporalGenerator(TemporalGenerator.TemporalType.HOUR, TemporalGenerator.TemporalType.MICROSECOND));
        basicGenerators.put("hour_second",
                new TemporalGenerator(TemporalGenerator.TemporalType.HOUR, TemporalGenerator.TemporalType.SECOND));
        basicGenerators.put("hour_minute",
                new TemporalGenerator(TemporalGenerator.TemporalType.HOUR, TemporalGenerator.TemporalType.MINUTE));
        basicGenerators.put("day_microsecond",
                new TemporalGenerator(TemporalGenerator.TemporalType.DAY, TemporalGenerator.TemporalType.MICROSECOND));
        basicGenerators.put("day_second",
                new TemporalGenerator(TemporalGenerator.TemporalType.DAY, TemporalGenerator.TemporalType.SECOND));
        basicGenerators.put("day_minute",
                new TemporalGenerator(TemporalGenerator.TemporalType.DAY, TemporalGenerator.TemporalType.MINUTE));
        basicGenerators.put("day_hour",
                new TemporalGenerator(TemporalGenerator.TemporalType.DAY, TemporalGenerator.TemporalType.HOUR));
        basicGenerators.put("year_month",
                new TemporalGenerator(TemporalGenerator.TemporalType.YEAR, TemporalGenerator.TemporalType.MONTH));

        basicGenerators.put("timestamp", new TimestampGenerator(""));

        basicGenerators.put("text", new TextGenerator(10));
        basicGenerators.put("bool", new BoolGenerator());
        basicGenerators.put("int4_unsigned", new IntGenerator(0, 15, ""));
        basicGenerators.put("int8", new IntGenerator(-128, 127, ""));
        basicGenerators.put("int8_unsigned", new IntGenerator(0, 255, ""));
        basicGenerators.put("int16", new IntGenerator(-32768, 32767, ""));
        basicGenerators.put("int16_unsigned", new IntGenerator(0, 65535, ""));
        basicGenerators.put("int5_16_unsigned", new IntGenerator(32, 65535, ""));
        basicGenerators.put("int24", new IntGenerator(-8388608, 8388607, ""));
        basicGenerators.put("int24_unsigned", new IntGenerator(0, 16777215, ""));
        basicGenerators.put("int32", new IntGenerator(-2147483648, 2147483647, ""));
        basicGenerators.put("int32_unsigned", new IntGenerator(0, 4294967295L, ""));
        basicGenerators.put("int64", new IntGenerator(0x8000000000000000L, 0x7fffffffffffffffL, ""));
        basicGenerators.put("int64_unsigned", new IntGenerator(0, 0x7fffffffffffffffL, ""));
        basicGenerators.put("decimal", new DecimalGenerator());
        basicGenerators.put("int_1_100000", new IntGenerator(1, 100000, ""));
        basicGenerators.put("int_0_715827882", new IntGenerator(0, 715827882, ""));
        basicGenerators.put("int_1_2147483647", new IntGenerator(1, 2147483647, ""));
        basicGenerators.put("int_1_10", new IntGenerator(1, 10, ""));
        basicGenerators.put("int_0_6", new IntGenerator(0, 6, ""));

        basicGenerators.put("float", new DoubleGenerator(-Float.MAX_VALUE, Float.MAX_VALUE, ""));
        basicGenerators.put("float_unsigned", new DoubleGenerator(0, Float.MAX_VALUE, ""));
        basicGenerators.put("float_0_1", new DoubleGenerator(0, 1, ""));
        basicGenerators.put("double", new DoubleGenerator(-Double.MAX_VALUE, Double.MAX_VALUE, ""));
        basicGenerators.put("double_unsigned", new DoubleGenerator(0, Double.MAX_VALUE, ""));

        // duckdb type aliases https://duckdb.org/docs/sql/data_types/numeric.html
        basicGenerators.put("boolean", new BoolGenerator());
        basicGenerators.put("int1", new IntGenerator(-128, 127, ""));
        basicGenerators.put("smallint", new IntGenerator(-32768, 32767, ""));
        basicGenerators.put("int2", new IntGenerator(-32768, 32767, ""));
        basicGenerators.put("short", new IntGenerator(-32768, 32767, ""));
        basicGenerators.put("int4", new IntGenerator(-2147483648, 2147483647, ""));
        basicGenerators.put("int", new IntGenerator(-2147483648, 2147483647, ""));
        basicGenerators.put("signed", new IntGenerator(-2147483648, 2147483647, ""));
        basicGenerators.put("bigint", new IntGenerator(Integer.MIN_VALUE, Integer.MAX_VALUE, ""));
        basicGenerators.put("hugeint", new DoubleGenerator(Double.MIN_VALUE, Double.MAX_VALUE, ""));
        basicGenerators.put("utinyint", new IntGenerator(0, 255, ""));
        basicGenerators.put("usmallint", new IntGenerator(0, 65535, ""));
        basicGenerators.put("uinteger", new DoubleGenerator(0, 4294967295.0, ""));
        basicGenerators.put("ubigint", new DoubleGenerator(0, Double.MAX_VALUE, ""));
        basicGenerators.put("float4", new DoubleGenerator(-3.40282e+38, 3.40282e+38, ""));

        // mysql type
        basicGenerators.put("bit", new BitGenerator());

        // postgresql inet
        basicGenerators.put("inet", new InetGenerator());
        basicGenerators.put("range", new RangeGenerator(Randomly.getBoolean(), Randomly.getBoolean()));

        // cockroachdb interval
        basicGenerators.put("interval", new IntervalGenerator());

        //dameng
        basicGenerators.put("numeric", new DoubleGenerator(Double.MAX_VALUE, Double.MAX_VALUE, ""));
        basicGenerators.put("doubleprecision", new DoubleGenerator(0, Double.MAX_VALUE, ""));
        basicGenerators.put("integer", new IntGenerator(Integer.MIN_VALUE, Integer.MAX_VALUE, ""));
        basicGenerators.put("byte", new IntGenerator(-128, 127, ""));
        basicGenerators.put("varbinary", new IntGenerator(0, 32767, ""));
        basicGenerators.put("longvarchar", new TextGenerator(10));
        basicGenerators.put("dec", new DoubleGenerator(Integer.MIN_VALUE, Integer.MAX_VALUE, ""));
        basicGenerators.put("varchar2", new TextGenerator(10));
        basicGenerators.put("longvarbinary", new IntGenerator(-128, 127, ""));
        basicGenerators.put("dmbit", new IntGenerator(0, 1, ""));
        basicGenerators.put("number", new DoubleGenerator(Double.MIN_VALUE, Double.MAX_VALUE, ""));
        basicGenerators.put("character", new CharGenerator());
        basicGenerators.put("long", new TextGenerator(10));
        basicGenerators.put("tinyint", new IntGenerator(-128, 127, ""));
    }

    private void initComposeGenerators(String defaultConfigPath) {
        composeGenerators = new HashMap<>();
        DBConfig.initDBConfig(defaultConfigPath);
        DBConfig dbConfig = DBConfig.getDBConfig();
        Map<String, List<String>> dataGeneratorConfig = dbConfig.getDataConfig();

        for (String dataType : dataGeneratorConfig.keySet()) {
            List<String> generatorOptions = dataGeneratorConfig.get(dataType);

            List<Generator> generators = new ArrayList<>();
            for (String option : generatorOptions) {
                Generator generator = basicGenerators.get(option);
                if (generator == null) {
                    generator = new ConstGenerator(option);
                }
                generators.add(generator);
            }
            composeGenerators.put(dataType.toLowerCase(), new ComposeGenerator(generators));
        }
    }

}
